baseURL = 'https://zachary-m-johnson.com/'
languageCode = 'en-us'
title = 'Zachary M. Johnson'
theme = 'ananke'

SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/zachary-m-johnson/"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/zmjohnso/"